version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
